## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np

In [3]:
x = np.array([[1,2,3], 
             [4,5,6]])
y = np.array([[7,8,9], 
             [10,1,2]])
z = x * y
z 

array([[ 7, 16, 27],
       [40,  5, 12]])

## Write a NumPy program to compute the determinant of a given square array

In [18]:
A = np.array([[-1,-2,-3], 
             [1,5,8],
             [2,7,4]
             ])
B= np.linalg.det(A)
B

20.99999999999999

## Write a NumPy program to compute the cross product of two given vectors

In [7]:
x = [[1,3], [5,8]]
y = [[4,9], [1,4]]
result = np.cross(x,y)
result

array([-3, 12])

In [9]:
result1 = np.cross(y,x)
result1

array([  3, -12])

## Write a NumPy program to compute the condition number of a given matrix

In [10]:
x = np.array([[1,2,3], 
             [-1,5,2], 
             [3,5,9]
             ])
z = np.linalg.cond(x)
z

109.05129390371098

## Write a NumPy program to compute the inverse of a given matrix

In [16]:
arr = np.array([[1,2],[4,5]])
z = np.linalg.inv(arr)
z

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [17]:
I = arr.dot(z)
I

array([[1., 0.],
       [0., 1.]])